displayName=Barrows with Benefits
author=SquidMuncher420
description=All-in-one Barrows helper with door highlights, tunnel memory, brother tracking & more.
tags=barrows,brothers,tunnel,crypt,reward,tracker
version=
plugins=com.barrowswithbenefits.BarrowsWithBenefitsPlugin
build=standard
